### ISSUE TITLE
mini todo list

### ISSUE THREAD

**Issue by zeffii** [zeffii/BlenderConsolePrompt#13]
`<  >` means optional
- [x] make bash executor for convert and gifsicle sequence
- [ ] add size check after rendering to gif (display size of any gifs found in /path/ - render.render.filepath)
   `>>> size </path/>`
- [ ] experiment with uploading to gifycat and copy the generated url ( http://gfycat.com/api ) 
  `>>> gcat /path/desired_image.gif`
- [ ] add BlenderPythonRecipes to pop up browser at `github.com/zeffii/BlenderPythonRecipes/wiki`
  `>>> bpr`
